### ISSUE TITLE
First installation feedback: unexpected keyword argument 'scope'

### ISSUE THREAD

**Issue by fradeve** [brettkromkamp/contextualise#32] opened 2020-02-09 20:19 UTC
Hi Brett,

first and foremost, thanks for opensourcing Contextualise!

I am giving it a try, and I incurred in an error when trying to open my first map. Here's how to reproduce it:

* logged in as `admin@` as per readme
* created new map with title, description and image (form won't save without an image)
* went to `http://127.0.0.1:5000/topics/view/1/home` and I got the following:

```
Traceback (most recent call last):
  File "/home/fradeve/.pyenv/versions/3.7.3/envs/contextualise/lib/python3.7/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/fradeve/.pyenv/versions/3.7.3/envs/contextualise/lib/python3.7/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/home/fradeve/.pyenv/versions/3.7.3/envs/contextualise/lib/python3.7/site-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/fradeve/.pyenv/versions/3.7.3/envs/contextualise/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/fradeve/.pyenv/versions/3.7.3/envs/contextualise/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/fradeve/.pyenv/versions/3.7.3/envs/contextualise/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/fradeve/.pyenv/versions/3.7.3/envs/contextualise/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/fradeve/.pyenv/versions/3.7.3/envs/contextualise/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/fradeve/.pyenv/versions/3.7.3/envs/contextualise/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/fradeve/.pyenv/versions/3.7.3/envs/contextualise/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/fradeve/contextualise/contextualise/topic.py", line 68, in view
    resolve_attributes=RetrievalMode.RESOLVE_ATTRIBUTES,
TypeError: get_topic() got an unexpected keyword argument 'scope'
```
Any idea of what might have gone wrong?

Thank you very much again!

**Comment by charlestondance** [comment] 2020-02-09 20:29
I am seeing the same issue would be great to know what is going on.

**Comment by brettkromkamp** [comment] 2020-02-09 20:31
@fradeve @charlestondance It must be related to a recent refactoring I did in relation to scopes. I'll take a look at it now.

**Comment by brettkromkamp** [comment] 2020-02-09 20:48
@fradeve @charlestondance I think I know what is causing the error: I have made some changes to TopicDB (https://github.com/brettkromkamp/topic-db), the topic map engine that Contextualise uses. Nonetheless, I haven't pushed the latest version to PyPI, yet. A temporary work-around would be to uninstall TopicDB (version 1.0) with `pip uninstall topic-db` followed by cloning TopicDB and doing a `pip install -e .` inside the project's top-level directory. Please let me know if this work-around works. In the meantime, I will publish the latest version of TopicDB to PyPI.

**Comment by fradeve** [comment] 2020-02-09 22:22
Hi @brettkromkamp,
thank you very much for your prompt response, I didn't expect that!

I have followed your instructions, and I got some progress, indeed.

Nonetheless, seems that a column is missing from the DB, since I now get this:

```
Traceback (most recent call last):
  File "/home/fradeve/.pyenv/versions/3.7.3/envs/contextualise/lib/python3.7/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/fradeve/.pyenv/versions/3.7.3/envs/contextualise/lib/python3.7/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/home/fradeve/.pyenv/versions/3.7.3/envs/contextualise/lib/python3.7/site-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/fradeve/.pyenv/versions/3.7.3/envs/contextualise/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/fradeve/.pyenv/versions/3.7.3/envs/contextualise/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/fradeve/.pyenv/versions/3.7.3/envs/contextualise/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/fradeve/.pyenv/versions/3.7.3/envs/contextualise/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/fradeve/.pyenv/versions/3.7.3/envs/contextualise/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/fradeve/.pyenv/versions/3.7.3/envs/contextualise/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/fradeve/.pyenv/versions/3.7.3/envs/contextualise/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/fradeve/contextualise/contextualise/topic.py", line 68, in view
    resolve_attributes=RetrievalMode.RESOLVE_ATTRIBUTES,
  File "/home/fradeve/contextualise/topic-db/topicdb/core/store/topicstore.py", line 1006, in get_topic
    cursor.execute(sql, bind_variables)
  File "/home/fradeve/.pyenv/versions/3.7.3/envs/contextualise/lib/python3.7/site-packages/psycopg2/extras.py", line 142, in execute
    return super(DictCursor, self).execute(query, vars)
psycopg2.errors.UndefinedColumn: column "scope" does not exist
LINE 1: SELECT name, scope, language, identifier
```

Is there any DB migration that I need to run as part of the installation process?

This is what my DB looks like at the moment:
```
 Schema |        Name        |   Type   |  Owner
--------+--------------------+----------+----------
 public | role               | table    | postgres
 public | role_id_seq        | sequence | postgres
 public | roles_users        | table    | postgres
 public | roles_users_id_seq | sequence | postgres
 public | user               | table    | postgres
 public | user_id_seq        | sequence | postgres
```

**Comment by brettkromkamp** [comment] 2020-02-09 22:43
@fradeve The problem is related to a recent refactoring in which I added a `scope` property to the `BaseName` class. However, I forgot to update the accompanying Contextualise/TopicDB database (SQL) creation script: https://gist.github.com/brettkromkamp/87aaa99b056578ff1dc23a43a49aca89

So, there is a `basename` table in the `contextualise` schema/database that requires the addition of the `scope` field. I'll provide a fix for this issue, sometime tomorrow. Sorry for the inconvenience.

**Comment by brettkromkamp** [comment] 2020-02-09 22:46
@fradeve By the way, it is my intention to make Contextualise publicly available (and free of charge) so as to avoid (potential) users from having to go through the convoluted setup process. I hope to publish Contextualise within the next week or so.

**Comment by brettkromkamp** [comment] 2020-03-08 07:00
@fradeve If you weren't already aware, Contextualise is now publicly available at: https://www.contextualise.dev/. I will be making available some short screen casts soon explaining how the application works: e.g., create a topic, edit a topic, add a note, upload an image to a topic, create an association and so forth.

**Comment by brettkromkamp** [comment] 2020-03-15 10:46
Closing issue. Instructions with a workaround have been provided (if installing locally). For those that don’t want to install locally, the application is publicly available at https://contextualise.dev.

**Closed by brettkromkamp** 2020-03-15 10:46 UTC
Labels: bug
